#!/bin/sh
#
# This script will compile the lab6 binaries.  Invoked without an
# argument, it will compile the basic lab6 program; with an argument,
# it will compile the trackball version.
#

if [ $# -gt 0 ]
then
	target="lab6track"
	srcfiles="lab6-trackball.cpp TrackBall.cpp"
else
	target="lab6"
	srcfiles="lab6.cpp"
fi

# echo the compilation command

set -x

g++ -g -o $target -I/home/fac/wrc/SOIL/include $srcfiles \
	ShaderSetup.cpp -framework GLUT -framework OpenGL
